# Generated by Django 4.2.3 on 2023-07-14 07:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0005_order_status_alter_cart_item_cart_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="users",
            new_name="user",
        ),
    ]
