# Generated by Django 4.2.3 on 2023-07-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0007_remove_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart_item",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cart_item",
            name="product",
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Cart"), (2, "ordered"), (3, "cancelled")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="order_detail",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="Cart_item",
        ),
    ]
