# Generated by Django 4.2.3 on 2023-07-17 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_product_image"),
        ("order", "0008_remove_cart_item_cart_remove_cart_item_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order_detail",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_pr",
                to="product.product",
            ),
        ),
    ]
