# Generated by Django 4.2.3 on 2023-07-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0009_alter_order_detail_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
