# Generated by Django 4.2.3 on 2023-07-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0010_alter_order_total"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="users",
            options={},
        ),
        migrations.AddField(
            model_name="users",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="phone",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterModelTable(
            name="users",
            table="auth_user",
        ),
    ]
