# Generated by Django 4.2.3 on 2023-07-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0018_users_street"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="avata",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
    ]
