# Generated by Django 4.2.2 on 2023-08-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0020_rename_avata_users_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("number", models.IntegerField(default=0)),
                ("email", models.EmailField(max_length=25)),
                ("message", models.TextField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
