# Generated by Django 4.2.3 on 2023-08-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0021_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
