# Generated by Django 4.2.3 on 2023-07-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_in_cart",
        ),
        migrations.AlterField(
            model_name="product",
            name="cost",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="product_information",
            name="pages",
            field=models.PositiveIntegerField(),
        ),
    ]
