# Generated by Django 4.2.3 on 2023-08-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_review_category_slug_product_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1
            ),
        ),
    ]
