# Generated by Django 4.2.3 on 2023-08-03 03:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_alter_review_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
    ]
