# Generated by Django 4.2.3 on 2023-08-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_remove_category_slug_remove_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(),
        ),
    ]
